version: '3'
services:
  backend:
    image: asyed755/composetest_backend
    ports:
     - "5000"
    links:
      - redis
  frontend:
    image: asyed755/composetest_frontend
    ports:
     - "80:80"
    links:
     - backend
  redis:
    image: "redis:alpine"
    ports:
     - "6379"
